import { chromium } from 'playwright';
import assert from 'node:assert/strict';
import { randomUUID } from 'node:crypto';
const base=process.argv[2].replace(/\/$/,''), origin=new URL(base).origin;
let browser,owner,bob,anon,page,docs,setupError;
const role=(p,r,name)=>p.getByRole(r,{name,exact:true});
const sleep=ms=>new Promise(r=>setTimeout(r,ms));
async function until(fn,ms=5000){let last; const end=performance.now()+ms; do{try{return await fn();}catch(e){last=e;}await sleep(40);}while(performance.now()<end);throw last;}
async function login(c,email,password){const p=await c.newPage();await p.goto(base+'/login');await p.getByLabel('Email',{exact:true}).fill(email);await p.getByLabel('Password',{exact:true}).fill(password);await role(p,'button','Sign in').click();await p.waitForURL(base+'/lists');return p;}
async function fresh(){const name='T3-'+randomUUID();await page.goto(base+'/lists/new');await page.getByLabel('Name',{exact:true}).fill(name);await role(page,'button','Create list').click();await page.waitForURL(u=>/^\/lists\/[^/]+$/.test(u.pathname)&&u.pathname!='/lists/new');await role(page,'heading',name).waitFor();return page.url();}
async function search(q){await page.getByLabel('Search books',{exact:true}).fill(q);const start=performance.now();await role(page,'button','Search').click({noWaitAfter:true});return start;}
function container(){return page.getByRole('region',{name:'Search results',exact:true}).or(page.getByRole('list',{name:'Search results',exact:true})).or(page.getByLabel('Search results',{exact:true}));}
async function mapped(){await until(async()=>{const c=container();assert.equal(await c.count(),1,'Missing Search results container');assert(await c.isVisible());const rows=c.getByRole('listitem');assert.equal(await rows.count(),docs.length,'Wrong result count');for(let i=0;i<docs.length;i++){const d=docs[i],r=rows.nth(i),text=await r.innerText();assert(await r.isVisible());if(d.title)assert(text.includes(d.title),'Title/order mismatch at '+i);if(d.author_name?.length)assert(text.includes(d.author_name[0]),'Author mismatch at '+i);if(d.first_publish_year!=null)assert(new RegExp('\\b'+d.first_publish_year+'\\b').test(text),'Year mismatch at '+i);assert.equal(await role(r,'button','Add').count(),1);}});return container().getByRole('listitem');}
async function recovery(){await search('dune');await mapped();}
async function books(){const h=role(page,'heading','Books');await h.waitFor();return h.evaluate(h=>{const section=h.closest('section,[role="region"]');if(section&&!section.querySelector('input'))return section.innerText;const texts=[],level=Number(h.tagName.slice(1))||2,w=document.createTreeWalker(document.body,NodeFilter.SHOW_ELEMENT);w.currentNode=h;while(w.nextNode()){const e=w.currentNode;if(h.contains(e))continue;if(/^H[1-6]$/.test(e.tagName)&&Number(e.tagName.slice(1))<=level)break;if(!e.children.length&&e.getClientRects().length)texts.push(e.innerText||e.textContent||'');}return texts.join('\n');});}
async function hasBook(n=1){await until(async()=>{const text=await books();assert.equal(text.split(docs[0].title).length-1,n,'Wrong number of book entries');if(n&&docs[0].author_name?.length)assert(text.includes(docs[0].author_name[0]),'Added author missing');});}
async function errorSearch(q,deadline,giveUp){const start=await search(q);await page.getByRole('alert').filter({hasText:'Book search is unavailable'}).first().waitFor({state:'visible',timeout:Math.max(1,deadline-(performance.now()-start))});const elapsed=performance.now()-start;assert(elapsed<=deadline,'Alert deadline exceeded');if(giveUp)assert(elapsed<=giveUp,'No observable abandonment within 5 s; alert at '+Math.round(elapsed)+' ms');await recovery();}
async function replay(c,r,cookies){const theirs=await c.cookies(r.url),headers={...r.headers};for(const name of Object.keys(headers)){if(['cookie','host','content-length'].includes(name.toLowerCase())){delete headers[name];continue;}let decoded=headers[name];try{decoded=decodeURIComponent(decoded);}catch{}const cookie=cookies.find(x=>x.value===headers[name]||x.value===decoded);if(cookie){const replacement=theirs.find(x=>x.name===cookie.name);if(replacement)headers[name]=headers[name]===cookie.value?replacement.value:encodeURIComponent(replacement.value);else delete headers[name];}}const response=await c.request.fetch(r.url,{method:r.method,headers,data:r.body??undefined,failOnStatusCode:false,timeout:10000});await response.dispose();}
try{browser=await chromium.launch({args:['--no-sandbox','--disable-dev-shm-usage']});owner=await browser.newContext();bob=await browser.newContext();anon=await browser.newContext();for(const c of [owner,bob,anon])c.setDefaultTimeout(10000);const response=await fetch('http://books:9100/search.json?q=dune&limit=10',{signal:AbortSignal.timeout(10000)});assert(response.ok);const data=await response.json();assert(Array.isArray(data.docs)&&data.docs.length);docs=data.docs.slice(0,10);page=await login(owner,'alice@example.test','Correct-Horse-1');}catch(e){setupError=e;}
const checks={
AC1:async()=>{await fresh();await recovery();},
AC2:async()=>{await fresh();await recovery();await search('zzzz-nothing');await page.getByText('No books found',{exact:true}).waitFor();assert.equal(await container().getByRole('listitem').count(),0,'Result items remain');assert.equal(await page.getByRole('listitem').filter({has:role(page,'button','Add')}).count(),0,'Add result items remain');},
AC3:async()=>{const errors=[];for(const q of ['__error__','__malformed__'])try{await fresh();await errorSearch(q,6000);}catch(e){errors.push(q+': '+e.message);}assert.equal(errors.length,0,errors.join('; '));},
AC4:async()=>{await fresh();await errorSearch('__timeout__',8000,5100);},
AC5:async()=>{await fresh();await recovery();await role((await mapped()).nth(0),'button','Add').click();await hasBook();await page.reload();await hasBook();await recovery();await role((await mapped()).nth(0),'button','Add').click();await hasBook();await page.reload();await hasBook();},
AC6:async()=>{await login(bob,'bob@example.test','Battery-Staple-2');const ap=await anon.newPage();await ap.goto(base);const errors=[];for(const [actor,c] of [['bob',bob],['anonymous',anon]])try{const url=await fresh();await recovery();await hasBook(0);const captured=[],pending=[];const record=req=>{if(new URL(req.url()).origin===origin&&!['GET','HEAD','OPTIONS'].includes(req.method()))pending.push(req.allHeaders().then(headers=>captured.push({url:req.url(),method:req.method(),body:req.postDataBuffer(),headers})));};const intercept=route=>{const req=route.request();return new URL(req.url()).origin===origin&&!['GET','HEAD','OPTIONS'].includes(req.method())?route.abort('failed'):route.continue();};page.on('request',record);await page.route('**/*',intercept);try{await role((await mapped()).nth(0),'button','Add').click();await until(async()=>assert(pending.length,'No add mutation captured'));await sleep(300);await Promise.all(pending);}finally{page.off('request',record);await page.unroute('**/*',intercept);}assert(captured.length,'No requests to replay');const cookies=await owner.cookies();await page.goto(url);const before=await books();await hasBook(0);for(const r of captured)await replay(c,r,cookies);await page.goto(url);assert.equal(await books(),before,actor+' changed Books');await hasBook(0);for(const r of captured)await replay(owner,r,cookies);await page.goto(url);await hasBook();}catch(e){errors.push(actor+': '+e.message);}assert.equal(errors.length,0,errors.join('; '));}
};
for(const [criterion,check] of Object.entries(checks)){try{if(setupError)throw setupError;await check();console.log(JSON.stringify({criterion,result:'pass'}));}catch(e){console.log(JSON.stringify({criterion,result:'fail',detail:String(e.message).slice(0,1200)}));}}
await browser?.close();process.exitCode=0;
